name: bookstore

services:
  books-db:
    image: postgres:alpine
    container_name: books-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5

  books-migration:
    image: migrate/migrate:v4.18.2
    container_name: books-migration
    volumes:
      - ./db:/migrations:ro,z
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        /migrate -path=/migrations/ -database "postgres://$${DB_USER}:$${DB_PASSWORD}@books-db:5432/$${DB_NAME}?sslmode=disable" up
    depends_on:
      books-db:
        condition: service_healthy
    restart: "no"

  books-api:
    container_name: books-api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:8080"
    environment:
      DB_HOST: books-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    depends_on:
      books-db:
        condition: service_healthy
      books-migration:
        condition: service_completed_successfully

volumes:
  db_data:
