name: bookstore

services:
  books-db:
    image: postgres:alpine
    container_name: books-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - .env

  books-api:
    container_name: books-api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:8080"
    environment:
      DB_HOST: books-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    depends_on:
      - books-db

volumes:
  db_data:
